variables:
  SRC_FOLDER: ${CI_PROJECT_NAME}
  DST_PORT: "5757"
  DEST_IP: "172.16.74.62"
  TEST_DST_FOLDER_PREFIX: "home_"

  ONLINE_DST_FOLDER: "vipress_docs"

before_script:
  - pwd

stages:
  - init

init_run:
  stage: init
  script:
    - ls /usr/
    - ls /usr/bin/rsync
    - user_name=`echo $GITLAB_USER_EMAIL |awk -F'@' '{print $1}'`
    - dst_dir="${DEST_IP}::${TEST_DST_FOLDER_PREFIX}${user_name}"
    - sync_cmd="/usr/bin/rsync -avczP --delete --exclude '.git' --port=${DST_PORT}  ../${SRC_FOLDER} ${dst_dir}"
    - echo "${sync_cmd}"
    - eval "${sync_cmd}"
  # only:
  #   - /^pre-.*$/


init_online:
  stage: init
  script:
      - echo "start launch_code"
      - echo "${SRC_FOLDER}-${ONLINE_DST_FOLDER}-${DST_PORT}"
      - /bin/bash .gitlab_code_launch.sh "${SRC_FOLDER}" "${ONLINE_DST_FOLDER}" "${DST_PORT}"
  # only:
  #     - /^versions-.*$/
  allow_failure: false