variables:
  DST_PORT: "5757"
  DEST_IP: "10.2.19.77"
  DST_RSYNC_PWD: "data_solution"             # 目标机 /etc/rsyncd.secrets
  CUST_APP_TAG_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_COMMIT_TAG   # runner机上的文件夹标识
  DST_FOLDER: "vipressdoc"


stages:
  - build
  - deploy

build_job:
  stage: build
  tags: 
    - "SSGRunnerSitA-172-16-74-63"
  script: 
    - export
    - npm i
    - npm run build
    - ls .




deploy_run_job:
  stage: deploy
  tags: 
    - "SSGRunnerSitA-172-16-74-63"
  script:
    - DIR=$(basename "$PWD")
    - echo "$DIR"
    - echo "backup ${DIR} to ${CUST_APP_TAG_NAME}"
    - cp -rf ../${DIR} ../${CUST_APP_TAG_NAME}
    - echo `pwd`
    - ls .
    - /usr/bin/rsync -avzP --delete  --port=5757  ./dist/ $DEST_IP::$DST_FOLDER  --exclude ".git"
  when: manual
